// Code generated by MockGen. DO NOT EDIT.
// Source: tools/aws/ecs/tools.go

// Package ecs is a generated GoMock package.
package ecs

import (
	context "context"
	reflect "reflect"

	builder "github.com/PointerByte/QuicksGo/logger/builder"
	ecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	gomock "github.com/golang/mock/gomock"
)

// MockecsAPI is a mock of ecsAPI interface.
type MockecsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockecsAPIMockRecorder
}

// MockecsAPIMockRecorder is the mock recorder for MockecsAPI.
type MockecsAPIMockRecorder struct {
	mock *MockecsAPI
}

// NewMockecsAPI creates a new mock instance.
func NewMockecsAPI(ctrl *gomock.Controller) *MockecsAPI {
	mock := &MockecsAPI{ctrl: ctrl}
	mock.recorder = &MockecsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockecsAPI) EXPECT() *MockecsAPIMockRecorder {
	return m.recorder
}

// DescribeTasks mocks base method.
func (m *MockecsAPI) DescribeTasks(ctx context.Context, params *ecs.DescribeTasksInput, optFns ...func(*ecs.Options)) (*ecs.DescribeTasksOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeTasks", varargs...)
	ret0, _ := ret[0].(*ecs.DescribeTasksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeTasks indicates an expected call of DescribeTasks.
func (mr *MockecsAPIMockRecorder) DescribeTasks(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeTasks", reflect.TypeOf((*MockecsAPI)(nil).DescribeTasks), varargs...)
}

// ListClusters mocks base method.
func (m *MockecsAPI) ListClusters(ctx context.Context, params *ecs.ListClustersInput, optFns ...func(*ecs.Options)) (*ecs.ListClustersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListClusters", varargs...)
	ret0, _ := ret[0].(*ecs.ListClustersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockecsAPIMockRecorder) ListClusters(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockecsAPI)(nil).ListClusters), varargs...)
}

// ListTasks mocks base method.
func (m *MockecsAPI) ListTasks(ctx context.Context, params *ecs.ListTasksInput, optFns ...func(*ecs.Options)) (*ecs.ListTasksOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTasks", varargs...)
	ret0, _ := ret[0].(*ecs.ListTasksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockecsAPIMockRecorder) ListTasks(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockecsAPI)(nil).ListTasks), varargs...)
}

// MocklistClustersPager is a mock of listClustersPager interface.
type MocklistClustersPager struct {
	ctrl     *gomock.Controller
	recorder *MocklistClustersPagerMockRecorder
}

// MocklistClustersPagerMockRecorder is the mock recorder for MocklistClustersPager.
type MocklistClustersPagerMockRecorder struct {
	mock *MocklistClustersPager
}

// NewMocklistClustersPager creates a new mock instance.
func NewMocklistClustersPager(ctrl *gomock.Controller) *MocklistClustersPager {
	mock := &MocklistClustersPager{ctrl: ctrl}
	mock.recorder = &MocklistClustersPagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistClustersPager) EXPECT() *MocklistClustersPagerMockRecorder {
	return m.recorder
}

// HasMorePages mocks base method.
func (m *MocklistClustersPager) HasMorePages() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMorePages")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasMorePages indicates an expected call of HasMorePages.
func (mr *MocklistClustersPagerMockRecorder) HasMorePages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMorePages", reflect.TypeOf((*MocklistClustersPager)(nil).HasMorePages))
}

// NextPage mocks base method.
func (m *MocklistClustersPager) NextPage(ctx context.Context, optFns ...func(*ecs.Options)) (*ecs.ListClustersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NextPage", varargs...)
	ret0, _ := ret[0].(*ecs.ListClustersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPage indicates an expected call of NextPage.
func (mr *MocklistClustersPagerMockRecorder) NextPage(ctx interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MocklistClustersPager)(nil).NextPage), varargs...)
}

// MocklistTasksPager is a mock of listTasksPager interface.
type MocklistTasksPager struct {
	ctrl     *gomock.Controller
	recorder *MocklistTasksPagerMockRecorder
}

// MocklistTasksPagerMockRecorder is the mock recorder for MocklistTasksPager.
type MocklistTasksPagerMockRecorder struct {
	mock *MocklistTasksPager
}

// NewMocklistTasksPager creates a new mock instance.
func NewMocklistTasksPager(ctrl *gomock.Controller) *MocklistTasksPager {
	mock := &MocklistTasksPager{ctrl: ctrl}
	mock.recorder = &MocklistTasksPagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistTasksPager) EXPECT() *MocklistTasksPagerMockRecorder {
	return m.recorder
}

// HasMorePages mocks base method.
func (m *MocklistTasksPager) HasMorePages() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMorePages")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasMorePages indicates an expected call of HasMorePages.
func (mr *MocklistTasksPagerMockRecorder) HasMorePages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMorePages", reflect.TypeOf((*MocklistTasksPager)(nil).HasMorePages))
}

// NextPage mocks base method.
func (m *MocklistTasksPager) NextPage(ctx context.Context, optFns ...func(*ecs.Options)) (*ecs.ListTasksOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NextPage", varargs...)
	ret0, _ := ret[0].(*ecs.ListTasksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPage indicates an expected call of NextPage.
func (mr *MocklistTasksPagerMockRecorder) NextPage(ctx interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MocklistTasksPager)(nil).NextPage), varargs...)
}

// MockIToolsECS is a mock of IToolsECS interface.
type MockIToolsECS struct {
	ctrl     *gomock.Controller
	recorder *MockIToolsECSMockRecorder
}

// MockIToolsECSMockRecorder is the mock recorder for MockIToolsECS.
type MockIToolsECSMockRecorder struct {
	mock *MockIToolsECS
}

// NewMockIToolsECS creates a new mock instance.
func NewMockIToolsECS(ctrl *gomock.Controller) *MockIToolsECS {
	mock := &MockIToolsECS{ctrl: ctrl}
	mock.recorder = &MockIToolsECSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToolsECS) EXPECT() *MockIToolsECSMockRecorder {
	return m.recorder
}

// GetTaskECSHosts mocks base method.
func (m *MockIToolsECS) GetTaskECSHosts(ctx context.Context, ctxLogger *builder.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskECSHosts", ctx, ctxLogger)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskECSHosts indicates an expected call of GetTaskECSHosts.
func (mr *MockIToolsECSMockRecorder) GetTaskECSHosts(ctx, ctxLogger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskECSHosts", reflect.TypeOf((*MockIToolsECS)(nil).GetTaskECSHosts), ctx, ctxLogger)
}
