// Code generated by MockGen. DO NOT EDIT.
// Source: IUnitary.go

// Package server_gRPC is a generated GoMock package.
package server_gRPC

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIUnitary is a mock of IUnitary interface.
type MockIUnitary struct {
	ctrl     *gomock.Controller
	recorder *MockIUnitaryMockRecorder
}

// MockIUnitaryMockRecorder is the mock recorder for MockIUnitary.
type MockIUnitaryMockRecorder struct {
	mock *MockIUnitary
}

// NewMockIUnitary creates a new mock instance.
func NewMockIUnitary(ctrl *gomock.Controller) *MockIUnitary {
	mock := &MockIUnitary{ctrl: ctrl}
	mock.recorder = &MockIUnitaryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUnitary) EXPECT() *MockIUnitaryMockRecorder {
	return m.recorder
}

// GetListener mocks base method.
func (m *MockIUnitary) GetListener() net.Listener {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListener")
	ret0, _ := ret[0].(net.Listener)
	return ret0
}

// GetListener indicates an expected call of GetListener.
func (mr *MockIUnitaryMockRecorder) GetListener() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListener", reflect.TypeOf((*MockIUnitary)(nil).GetListener))
}

// GetServer mocks base method.
func (m *MockIUnitary) GetServer() *grpc.Server {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer")
	ret0, _ := ret[0].(*grpc.Server)
	return ret0
}

// GetServer indicates an expected call of GetServer.
func (mr *MockIUnitaryMockRecorder) GetServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockIUnitary)(nil).GetServer))
}

// GracefulStop mocks base method.
func (m *MockIUnitary) GracefulStop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulStop")
}

// GracefulStop indicates an expected call of GracefulStop.
func (mr *MockIUnitaryMockRecorder) GracefulStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulStop", reflect.TypeOf((*MockIUnitary)(nil).GracefulStop))
}

// Register mocks base method.
func (m *MockIUnitary) Register(register RegisterServiceFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", register)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIUnitaryMockRecorder) Register(register interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIUnitary)(nil).Register), register)
}

// Serve mocks base method.
func (m *MockIUnitary) Serve() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve")
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockIUnitaryMockRecorder) Serve() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockIUnitary)(nil).Serve))
}

// SetAddress mocks base method.
func (m *MockIUnitary) SetAddress(address string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAddress", address)
}

// SetAddress indicates an expected call of SetAddress.
func (mr *MockIUnitaryMockRecorder) SetAddress(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAddress", reflect.TypeOf((*MockIUnitary)(nil).SetAddress), address)
}

// SetListener mocks base method.
func (m *MockIUnitary) SetListener(listener net.Listener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetListener", listener)
}

// SetListener indicates an expected call of SetListener.
func (mr *MockIUnitaryMockRecorder) SetListener(listener interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetListener", reflect.TypeOf((*MockIUnitary)(nil).SetListener), listener)
}

// Stop mocks base method.
func (m *MockIUnitary) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockIUnitaryMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIUnitary)(nil).Stop))
}
