// Copyright 2026 PointerByte Contributors
// SPDX-License-Identifier: Apache-2.0

package local

import (
	"crypto"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ed25519"
	"crypto/hmac"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/PointerByte/QuicksGo/security/encrypt/common"
	"github.com/zeebo/blake3"
)

type symmetricRepository struct{}

// NewSymmetricRepository returns a SymmetricRepository implementation backed by
// the package helpers.
func NewSymmetricRepository() SymmetricRepository {
	return &symmetricRepository{}
}

// GeneratesSymetrycKey creates a random symmetric key and returns it in Base64
// form.
func (symmetricRepository) GeneratesSymetrycKey(size common.SizeSymetrycKey) (string, error) {
	b := make([]byte, size)
	_, err := io.ReadFull(rand.Reader, b)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(b), nil
}

// EncryptAES encrypts plaintext using AES-GCM with a Base64-encoded key and
// optional additional authenticated data.
func (symmetricRepository) EncryptAES(symmetricalAccess, valorCampo, additionalData string) (string, error) {
	aesKeyBytes, err := base64.StdEncoding.DecodeString(symmetricalAccess)
	if err != nil {
		return "", fmt.Errorf("decode AES key: %w", err)
	}

	block, err := aes.NewCipher(aesKeyBytes)
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create GCM: %w", err)
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", fmt.Errorf("generate nonce: %w", err)
	}

	cipherText := gcm.Seal(nil, nonce, []byte(valorCampo), []byte(additionalData))
	payload := append(nonce, cipherText...)
	return base64.StdEncoding.EncodeToString(payload), nil
}

// DecryptAES decrypts ciphertext generated by EncryptAES.
func (symmetricRepository) DecryptAES(symmetricalAccess, valorCifrado, additionalData string) (string, error) {
	aesKeyBytes, err := base64.StdEncoding.DecodeString(symmetricalAccess)
	if err != nil {
		return "", fmt.Errorf("decode AES key: %w", err)
	}

	block, err := aes.NewCipher(aesKeyBytes)
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create GCM: %w", err)
	}

	allBytes, err := base64.StdEncoding.DecodeString(valorCifrado)
	if err != nil {
		return "", fmt.Errorf("decode Base64 ciphertext: %w", err)
	}

	if len(allBytes) < gcm.NonceSize() {
		return "", errors.New("ciphertext is too short")
	}

	nonce := allBytes[:gcm.NonceSize()]
	cipherText := allBytes[gcm.NonceSize():]
	plainText, err := gcm.Open(nil, nonce, cipherText, []byte(additionalData))
	if err != nil {
		return "", fmt.Errorf("decrypt AES-GCM: %w", err)
	}
	return string(plainText), nil
}

type fernetKey struct {
	signingKey    []byte
	encryptionKey []byte
}

func decodeFernetKey(b64 string) (*fernetKey, error) {
	keyBytes, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, err
	}
	if len(keyBytes) != 32 {
		return nil, errors.New("fernet key must be 32 bytes")
	}

	return &fernetKey{
		signingKey:    keyBytes[:16],
		encryptionKey: keyBytes[16:32],
	}, nil
}

// EncodeFernet creates a Fernet-compatible token from plaintext using the
// provided Base64 key.
func (symmetricRepository) EncodeFernet(keyString, originalString string) (string, error) {
	key, err := decodeFernetKey(keyString)
	if err != nil {
		return "", err
	}

	// Version (0x80) and timestamp (8 bytes).
	token := make([]byte, 9)
	token[0] = 0x80
	ts := uint64(time.Now().Unix())
	for i := range 8 {
		token[8-i] = byte(ts & 0xff)
		ts >>= 8
	}

	// Random 16-byte IV.
	iv := make([]byte, 16)
	_, err = rand.Read(iv)
	if err != nil {
		return "", err
	}
	token = append(token, iv...)

	// AES-CBC encryption.
	block, err := aes.NewCipher(key.encryptionKey)
	if err != nil {
		return "", err
	}

	plaintext := pkcs7Pad([]byte(originalString), aes.BlockSize)
	ciphertext := make([]byte, len(plaintext))
	mode := cipher.NewCBCEncrypter(block, iv)
	mode.CryptBlocks(ciphertext, plaintext)
	token = append(token, ciphertext...)

	// HMAC-SHA256 over the complete token body.
	mac := hmac.New(sha256.New, key.signingKey)
	mac.Write(token)
	signature := mac.Sum(nil)
	token = append(token, signature...)
	return base64.URLEncoding.EncodeToString(token), nil
}

// DecodeFernet validates and decrypts a Fernet-compatible token.
func (symmetricRepository) DecodeFernet(keyString, encryptedString string) (string, error) {
	key, err := decodeFernetKey(keyString)
	if err != nil {
		return "", err
	}

	token, err := base64.URLEncoding.DecodeString(encryptedString)
	if err != nil {
		return "", err
	}
	if len(token) < 9+16+32 {
		return "", errors.New("fernet token is too short")
	}

	// Split message and signature.
	message := token[:len(token)-32]
	signature := token[len(token)-32:]

	// Validate HMAC.
	mac := hmac.New(sha256.New, key.signingKey)
	mac.Write(message)
	expected := mac.Sum(nil)
	if !hmac.Equal(expected, signature) {
		return "", errors.New("invalid HMAC signature")
	}

	// Extract IV and ciphertext.
	iv := message[9 : 9+16]
	ciphertext := message[9+16:]

	// AES-CBC decryption.
	block, err := aes.NewCipher(key.encryptionKey)
	if err != nil {
		return "", err
	}

	if len(ciphertext)%aes.BlockSize != 0 {
		return "", errors.New("ciphertext is not a multiple of the block size")
	}

	plaintext := make([]byte, len(ciphertext))
	mode := cipher.NewCBCDecrypter(block, iv)
	mode.CryptBlocks(plaintext, ciphertext)

	plaintext, err = pkcs7Unpad(plaintext, aes.BlockSize)
	if err != nil {
		return "", err
	}
	return string(plaintext), nil
}

type hashRepository struct{}

// NewHashRepository returns a HashRepository implementation.
func NewHashRepository() HashRepository {
	return &hashRepository{}
}

// GenerateHMAC returns a Base64-encoded HMAC-SHA256 signature.
func (hashRepository) GenerateHMAC(message, secretKey string) string {
	h := hmac.New(sha256.New, []byte(secretKey))
	h.Write([]byte(message))
	return base64.StdEncoding.EncodeToString(h.Sum(nil))
}

// ValidateHMAC checks whether providedHash matches the HMAC of message.
func (sr hashRepository) ValidateHMAC(message, secretKey, providedHash string) bool {
	expectedHash := sr.GenerateHMAC(message, secretKey)
	return hmac.Equal([]byte(expectedHash), []byte(providedHash))
}

// Sha256Hex returns the SHA-256 digest of message encoded in hexadecimal.
func (hashRepository) Sha256Hex(message string) string {
	hash := sha256.Sum256([]byte(message))
	return hex.EncodeToString(hash[:])
}

// Blake3 returns the BLAKE3 digest of message encoded in Base64.
func (hashRepository) Blake3(message string) string {
	hash := blake3.Sum256([]byte(message))
	return base64.StdEncoding.EncodeToString(hash[:])
}

type asymmetricRepository struct{}

// NewAsymmetricRepository returns an AsymmetricRepository implementation.
func NewAsymmetricRepository() AsymmetricRepository {
	return &asymmetricRepository{}
}

// GeneratesRSAKey creates an RSA key pair and returns both keys encoded in
// Base64.
func (asymmetricRepository) GeneratesRSAKey(size common.SizeAsymetrycKey) (priv string, pub string, _ error) {
	privateKey, err := rsa.GenerateKey(rand.Reader, int(size))
	if err != nil {
		return "", "", err
	}
	privDer := x509.MarshalPKCS1PrivateKey(privateKey)
	priv = base64.StdEncoding.EncodeToString(privDer)
	publicKey := &privateKey.PublicKey
	publicDer := x509.MarshalPKCS1PublicKey(publicKey)
	pub = base64.StdEncoding.EncodeToString(publicDer)
	return
}

// RSA_OAEP_Encode encrypts plaintext with RSA-OAEP using a Base64-encoded
// public key.
func (asymmetricRepository) RSA_OAEP_Encode(key, text string) (string, error) {
	pub, err := ParseRSAPublicKeyFromBase64(key)
	if err != nil {
		return "", fmt.Errorf("load public key: %w", err)
	}

	hash := sha256.New()
	cipherBytes, err := rsa.EncryptOAEP(hash, rand.Reader, pub, []byte(text), nil)
	if err != nil {
		return "", fmt.Errorf("encrypt with RSA-OAEP: %w", err)
	}
	return base64.StdEncoding.EncodeToString(cipherBytes), nil
}

// RSA_OAEP_Decode decrypts Base64 ciphertext with RSA-OAEP using a Base64-
// encoded private key.
func (asymmetricRepository) RSA_OAEP_Decode(key, text string) (string, error) {
	priv, err := ParseRSAPrivateKeyFromBase64(key)
	if err != nil {
		return "", fmt.Errorf("load private key: %w", err)
	}

	encrypted, err := base64.StdEncoding.DecodeString(text)
	if err != nil {
		return "", fmt.Errorf("decode Base64 ciphertext: %w", err)
	}

	hash := sha256.New()
	plainBytes, err := rsa.DecryptOAEP(hash, rand.Reader, priv, encrypted, nil)
	if err != nil {
		return "", fmt.Errorf("decrypt with RSA-OAEP: %w", err)
	}
	return string(plainBytes), nil
}

type signatureRepository struct{}

// NewSignatureRepository returns a SignatureRepository implementation.
func NewSignatureRepository() SignatureRepository {
	return &signatureRepository{}
}

// GeneratesEd255Key creates an Ed25519 key pair encoded in Base64.
func (signatureRepository) GeneratesEd255Key(size common.SizeAsymetrycKey) (priv string, pub string, _ error) {
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return "", "", err
	}

	privDer, err := x509.MarshalPKCS8PrivateKey(privateKey)
	if err != nil {
		return "", "", err
	}
	priv = base64.StdEncoding.EncodeToString(privDer)

	publicDer, err := x509.MarshalPKIXPublicKey(publicKey)
	if err != nil {
		return "", "", err
	}
	pub = base64.StdEncoding.EncodeToString(publicDer)
	return
}

// SignEd25519 signs text using a Base64-encoded Ed25519 private key.
func (sr signatureRepository) SignEd25519(key, text string) (string, error) {
	privateKey, err := ParseEd25519PrivateKeyFromBase64(key)
	if err != nil {
		return "", fmt.Errorf("load private key: %w", err)
	}

	signature := ed25519.Sign(privateKey, []byte(text))
	return base64.StdEncoding.EncodeToString(signature), nil
}

// VerifyEd25519 verifies a Base64-encoded Ed25519 signature.
func (sr signatureRepository) VerifyEd25519(key, text, signature string) error {
	publicKey, err := ParseEd25519PublicKeyFromBase64(key)
	if err != nil {
		return fmt.Errorf("load public key: %w", err)
	}

	signatureBytes, err := base64.StdEncoding.DecodeString(signature)
	if err != nil {
		return fmt.Errorf("decode signature from Base64: %w", err)
	}

	if !ed25519.Verify(publicKey, []byte(text), signatureBytes) {
		return errors.New("invalid Ed25519 signature")
	}
	return nil
}

// SignRSAPSS signs text using RSA-PSS and returns the signature in Base64.
func (signatureRepository) SignRSAPSS(key, text string) (string, error) {
	priv, err := ParseRSAPrivateKeyFromBase64(key)
	if err != nil {
		return "", fmt.Errorf("load private key: %w", err)
	}

	hashed := sha256.Sum256([]byte(text))
	signature, err := rsa.SignPSS(rand.Reader, priv, crypto.SHA256, hashed[:], nil)
	if err != nil {
		return "", fmt.Errorf("sign with RSA-PSS: %w", err)
	}
	return base64.StdEncoding.EncodeToString(signature), nil
}

// VerifyRSAPSS verifies a Base64-encoded RSA-PSS signature.
func (signatureRepository) VerifyRSAPSS(key, text, signature string) error {
	pub, err := ParseRSAPublicKeyFromBase64(key)
	if err != nil {
		return fmt.Errorf("load public key: %w", err)
	}

	signatureBytes, err := base64.StdEncoding.DecodeString(signature)
	if err != nil {
		return fmt.Errorf("decode signature from Base64: %w", err)
	}

	hashed := sha256.Sum256([]byte(text))
	if err := rsa.VerifyPSS(pub, crypto.SHA256, hashed[:], signatureBytes, nil); err != nil {
		return fmt.Errorf("invalid RSA-PSS signature: %w", err)
	}
	return nil
}

// SignSHA256 signs data with RSA PKCS#1 v1.5 using SHA-256 and returns the
// signature in Base64.
func (signatureRepository) SignSHA256(data string, privateKey *rsa.PrivateKey) (string, error) {
	if privateKey == nil {
		return "", errors.New("private key is required")
	}

	hashed := sha256.Sum256([]byte(data))
	signature, err := rsa.SignPKCS1v15(rand.Reader, privateKey, crypto.SHA256, hashed[:])
	if err != nil {
		return "", fmt.Errorf("sign with RSA SHA-256: %w", err)
	}
	return base64.StdEncoding.EncodeToString(signature), nil
}

// VerifySHA256 verifies a Base64-encoded RSA PKCS#1 v1.5 SHA-256 signature.
func (signatureRepository) VerifySHA256(data, signature string, publicKey *rsa.PublicKey) error {
	if publicKey == nil {
		return errors.New("public key is required")
	}

	hashed := sha256.Sum256([]byte(data))
	_signature, err := base64.StdEncoding.DecodeString(signature)
	if err != nil {
		return err
	}
	if err := rsa.VerifyPKCS1v15(publicKey, crypto.SHA256, hashed[:], []byte(_signature)); err != nil {
		return fmt.Errorf("invalid RSA SHA-256 signature: %w", err)
	}
	return nil
}

type repository struct {
	SymmetricRepository
	AsymmetricRepository
	SignatureRepository
	HashRepository
}

// NewRepository returns a combined repository with the main cryptographic
// capabilities exposed by this package.
func NewRepository() *repository {
	return &repository{
		NewSymmetricRepository(),
		NewAsymmetricRepository(),
		NewSignatureRepository(),
		NewHashRepository(),
	}
}
