// Copyright 2026 PointerByte Contributors
// SPDX-License-Identifier: Apache-2.0

package local

import (
	"context"
	"crypto"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ed25519"
	"crypto/hmac"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"

	"github.com/PointerByte/QuicksGo/encrypt/common"
	"github.com/PointerByte/QuicksGo/encrypt/models"
	"github.com/zeebo/blake3"
)

type symmetricRepository struct{}

// NewSymmetricRepository returns a SymmetricRepository implementation backed by
// the package helpers.
func NewSymmetricRepository() SymmetricRepository {
	return &symmetricRepository{}
}

// GeneratesSymetrycKey creates a random symmetric key and returns it in Base64
// form.
func (symmetricRepository) GeneratesSymetrycKey(ctx context.Context, size common.SizeSymetrycKey) (*models.SymmetricKeyData, error) {
	_ = ctx
	if err := validateSymmetricKeySize(size); err != nil {
		return nil, err
	}

	b := make([]byte, size)
	_, err := io.ReadFull(rand.Reader, b)
	if err != nil {
		return nil, err
	}
	return &models.SymmetricKeyData{
		KeyID:    base64.StdEncoding.EncodeToString(b),
		Provider: "local",
	}, nil
}

// EncryptAES encrypts plaintext using AES-GCM with a Base64-encoded key and
// optional additional authenticated data.
func (symmetricRepository) EncryptAES(ctx context.Context, secretKey, value string, additional *string) (string, error) {
	_ = ctx
	aesKeyBytes, err := base64.StdEncoding.DecodeString(secretKey)
	if err != nil {
		return "", fmt.Errorf("decode AES key: %w", err)
	}

	block, err := aes.NewCipher(aesKeyBytes)
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create GCM: %w", err)
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", fmt.Errorf("generate nonce: %w", err)
	}

	cipherText := gcm.Seal(nil, nonce, []byte(value), bytesFromOptionalString(additional))
	payload := append(nonce, cipherText...)
	return base64.StdEncoding.EncodeToString(payload), nil
}

// DecryptAES decrypts ciphertext generated by EncryptAES.
func (symmetricRepository) DecryptAES(ctx context.Context, secretKey, cipherValue string, additional *string) (string, error) {
	_ = ctx
	aesKeyBytes, err := base64.StdEncoding.DecodeString(secretKey)
	if err != nil {
		return "", fmt.Errorf("decode AES key: %w", err)
	}

	block, err := aes.NewCipher(aesKeyBytes)
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create GCM: %w", err)
	}

	allBytes, err := base64.StdEncoding.DecodeString(cipherValue)
	if err != nil {
		return "", fmt.Errorf("decode Base64 ciphertext: %w", err)
	}

	if len(allBytes) < gcm.NonceSize() {
		return "", errors.New("ciphertext is too short")
	}

	nonce := allBytes[:gcm.NonceSize()]
	cipherText := allBytes[gcm.NonceSize():]
	plainText, err := gcm.Open(nil, nonce, cipherText, bytesFromOptionalString(additional))
	if err != nil {
		return "", fmt.Errorf("decrypt AES-GCM: %w", err)
	}
	return string(plainText), nil
}

func bytesFromOptionalString(value *string) []byte {
	if value == nil {
		return nil
	}
	return []byte(*value)
}

type hashRepository struct{}

// NewHashRepository returns a HashRepository implementation.
func NewHashRepository() HashRepository {
	return &hashRepository{}
}

// GenerateHMAC returns a Base64-encoded HMAC-SHA256 signature.
func (hashRepository) GenerateHMAC(ctx context.Context, secretKey, message string) string {
	_ = ctx
	h := hmac.New(sha256.New, []byte(secretKey))
	h.Write([]byte(message))
	return base64.StdEncoding.EncodeToString(h.Sum(nil))
}

// ValidateHMAC checks whether providedHash matches the HMAC of message.
func (sr hashRepository) ValidateHMAC(ctx context.Context, secretKey, message, providedHash string) bool {
	expectedHash := sr.GenerateHMAC(ctx, secretKey, message)
	return hmac.Equal([]byte(expectedHash), []byte(providedHash))
}

// Sha256Hex returns the SHA-256 digest of message encoded in hexadecimal.
func (hashRepository) Sha256Hex(ctx context.Context, message string) string {
	_ = ctx
	hash := sha256.Sum256([]byte(message))
	return hex.EncodeToString(hash[:])
}

// Blake3 returns the BLAKE3 digest of message encoded in Base64.
func (hashRepository) Blake3(ctx context.Context, message string) string {
	_ = ctx
	hash := blake3.Sum256([]byte(message))
	return base64.StdEncoding.EncodeToString(hash[:])
}

type asymmetricRepository struct{}

// NewAsymmetricRepository returns an AsymmetricRepository implementation.
func NewAsymmetricRepository() AsymmetricRepository {
	return &asymmetricRepository{}
}

// GeneratesRSAKey creates an RSA key pair and returns both keys encoded in
// Base64.
func (asymmetricRepository) GeneratesRSAKey(ctx context.Context, size common.SizeAsymetrycKey) (*models.AsymmetricKeyData, error) {
	_ = ctx
	if err := validateAsymmetricKeySize(size); err != nil {
		return nil, err
	}

	privateKey, err := rsa.GenerateKey(rand.Reader, int(size))
	if err != nil {
		return nil, err
	}
	privDer := x509.MarshalPKCS1PrivateKey(privateKey)
	priv := base64.StdEncoding.EncodeToString(privDer)
	publicKey := &privateKey.PublicKey
	publicDer := x509.MarshalPKCS1PublicKey(publicKey)
	pub := base64.StdEncoding.EncodeToString(publicDer)
	return &models.AsymmetricKeyData{
		PrivateKey: priv,
		PublicKey:  pub,
		Provider:   "local",
	}, nil
}

// RSA_OAEP_Encode encrypts plaintext with RSA-OAEP using a Base64-encoded
// public key.
func (asymmetricRepository) RSA_OAEP_Encode(ctx context.Context, publicKey, text string) (string, error) {
	_ = ctx
	pub, err := ParseRSAPublicKeyFromBase64(publicKey)
	if err != nil {
		return "", fmt.Errorf("load public key: %w", err)
	}

	hash := sha256.New()
	cipherBytes, err := rsa.EncryptOAEP(hash, rand.Reader, pub, []byte(text), nil)
	if err != nil {
		return "", fmt.Errorf("encrypt with RSA-OAEP: %w", err)
	}
	return base64.StdEncoding.EncodeToString(cipherBytes), nil
}

// RSA_OAEP_Decode decrypts Base64 ciphertext with RSA-OAEP using a Base64-
// encoded private key.
func (asymmetricRepository) RSA_OAEP_Decode(ctx context.Context, privateKey, cipherText string) (string, error) {
	_ = ctx
	priv, err := ParseRSAPrivateKeyFromBase64(privateKey)
	if err != nil {
		return "", fmt.Errorf("load private key: %w", err)
	}

	encrypted, err := base64.StdEncoding.DecodeString(cipherText)
	if err != nil {
		return "", fmt.Errorf("decode Base64 ciphertext: %w", err)
	}

	hash := sha256.New()
	plainBytes, err := rsa.DecryptOAEP(hash, rand.Reader, priv, encrypted, nil)
	if err != nil {
		return "", fmt.Errorf("decrypt with RSA-OAEP: %w", err)
	}
	return string(plainBytes), nil
}

type signatureRepository struct{}

// NewSignatureRepository returns a SignatureRepository implementation.
func NewSignatureRepository() SignatureRepository {
	return &signatureRepository{}
}

// GeneratesEd255Key creates an Ed25519 key pair encoded in Base64.
func (signatureRepository) GeneratesEd255Key(ctx context.Context, size common.SizeAsymetrycKey) (*models.AsymmetricKeyData, error) {
	_ = ctx
	_ = size
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, err
	}

	privDer, err := x509.MarshalPKCS8PrivateKey(privateKey)
	if err != nil {
		return nil, err
	}
	priv := base64.StdEncoding.EncodeToString(privDer)

	publicDer, err := x509.MarshalPKIXPublicKey(publicKey)
	if err != nil {
		return nil, err
	}
	pub := base64.StdEncoding.EncodeToString(publicDer)
	return &models.AsymmetricKeyData{
		PrivateKey: priv,
		PublicKey:  pub,
		Provider:   "local",
	}, nil
}

func validateSymmetricKeySize(size common.SizeSymetrycKey) error {
	switch size {
	case common.Key128Bits, common.Key256Bits:
		return nil
	default:
		return fmt.Errorf("unsupported symmetric key size: %d", size)
	}
}

func validateAsymmetricKeySize(size common.SizeAsymetrycKey) error {
	switch size {
	case common.Key2048Bits, common.Key3072Bits, common.Key4096Bits:
		return nil
	default:
		return fmt.Errorf("unsupported asymmetric key size: %d", size)
	}
}

// SignEd25519 signs text using a Base64-encoded Ed25519 private key.
func (sr signatureRepository) SignEd25519(ctx context.Context, privateKey, text string) (string, error) {
	_ = ctx
	ed25519PrivateKey, err := ParseEd25519PrivateKeyFromBase64(privateKey)
	if err != nil {
		return "", fmt.Errorf("load private key: %w", err)
	}

	signature := ed25519.Sign(ed25519PrivateKey, []byte(text))
	return base64.StdEncoding.EncodeToString(signature), nil
}

// VerifyEd25519 verifies a Base64-encoded Ed25519 signature.
func (sr signatureRepository) VerifyEd25519(ctx context.Context, publicKey, text, signature string) error {
	_ = ctx
	ed25519PublicKey, err := ParseEd25519PublicKeyFromBase64(publicKey)
	if err != nil {
		return fmt.Errorf("load public key: %w", err)
	}

	signatureBytes, err := base64.StdEncoding.DecodeString(signature)
	if err != nil {
		return fmt.Errorf("decode signature from Base64: %w", err)
	}

	if !ed25519.Verify(ed25519PublicKey, []byte(text), signatureBytes) {
		return errors.New("invalid Ed25519 signature")
	}
	return nil
}

// SignRSAPSS signs text using RSA-PSS and returns the signature in Base64.
func (signatureRepository) SignRSAPSS(ctx context.Context, privateKey, text string) (string, error) {
	_ = ctx
	priv, err := ParseRSAPrivateKeyFromBase64(privateKey)
	if err != nil {
		return "", fmt.Errorf("load private key: %w", err)
	}

	hashed := sha256.Sum256([]byte(text))
	signature, err := rsa.SignPSS(rand.Reader, priv, crypto.SHA256, hashed[:], nil)
	if err != nil {
		return "", fmt.Errorf("sign with RSA-PSS: %w", err)
	}
	return base64.StdEncoding.EncodeToString(signature), nil
}

// VerifyRSAPSS verifies a Base64-encoded RSA-PSS signature.
func (signatureRepository) VerifyRSAPSS(ctx context.Context, publicKey, text, signature string) error {
	_ = ctx
	pub, err := ParseRSAPublicKeyFromBase64(publicKey)
	if err != nil {
		return fmt.Errorf("load public key: %w", err)
	}

	signatureBytes, err := base64.StdEncoding.DecodeString(signature)
	if err != nil {
		return fmt.Errorf("decode signature from Base64: %w", err)
	}

	hashed := sha256.Sum256([]byte(text))
	if err := rsa.VerifyPSS(pub, crypto.SHA256, hashed[:], signatureBytes, nil); err != nil {
		return fmt.Errorf("invalid RSA-PSS signature: %w", err)
	}
	return nil
}

// SignPKCS1v15_SHA256 signs data with RSA PKCS#1 v1.5 using SHA-256 and returns the
// signature in Base64.
func (signatureRepository) SignPKCS1v15_SHA256(ctx context.Context, data string, privateKey *rsa.PrivateKey) (string, error) {
	_ = ctx
	if privateKey == nil {
		return "", errors.New("private key is required")
	}

	hashed := sha256.Sum256([]byte(data))
	signature, err := rsa.SignPKCS1v15(rand.Reader, privateKey, crypto.SHA256, hashed[:])
	if err != nil {
		return "", fmt.Errorf("sign with RSA SHA-256: %w", err)
	}
	return base64.StdEncoding.EncodeToString(signature), nil
}

// VerifySHA256 verifies a Base64-encoded RSA PKCS#1 v1.5 SHA-256 signature.
func (signatureRepository) VerifySHA256(ctx context.Context, data, signature string, publicKey *rsa.PublicKey) error {
	_ = ctx
	if publicKey == nil {
		return errors.New("public key is required")
	}

	hashed := sha256.Sum256([]byte(data))
	_signature, err := base64.StdEncoding.DecodeString(signature)
	if err != nil {
		return err
	}
	if err := rsa.VerifyPKCS1v15(publicKey, crypto.SHA256, hashed[:], []byte(_signature)); err != nil {
		return fmt.Errorf("invalid RSA SHA-256 signature: %w", err)
	}
	return nil
}

type Repository struct {
	SymmetricRepository
	AsymmetricRepository
	SignatureRepository
	HashRepository
}

// NewRepository returns a combined repository with the main cryptographic
// capabilities exposed by this package.
func NewRepository() *Repository {
	return &Repository{
		NewSymmetricRepository(),
		NewAsymmetricRepository(),
		NewSignatureRepository(),
		NewHashRepository(),
	}
}
